import {
  createVizSettingDefaults,
  defineVizComponentAuthoring,
  field,
  v,
} from '@viz-engine/components-core';

const signalCathedralConfig = v.config({
  palette: field.group(
    'Palette',
    "The scene's architectural and atmospheric colors.",
    {
      background: field.color(
        'Background',
        '#02030d',
        'Deep background color behind the structure.',
      ),
      primary: field.color(
        'Primary Light',
        '#5cf5ff',
        'Main arch and core color.',
      ),
      secondary: field.color(
        'Secondary Light',
        '#8b5cff',
        'Alternating structural light color.',
      ),
      accent: field.color(
        'Accent',
        '#ff3fcf',
        'Shockwave and high-frequency accent color.',
      ),
      fog: field.color('Fog', '#07051c', 'Atmospheric depth color.'),
    },
  ),
  structure: field.group(
    'Structure',
    'Dimensions and density of the luminous cathedral.',
    {
      archCount: field.number(
        'Arch Count',
        24,
        [8, 32, 1],
        'Number of repeating arch gates.',
      ),
      archSpacing: field.number(
        'Arch Spacing',
        4.2,
        [2, 8, 0.1],
        'Depth between consecutive gates.',
      ),
      naveWidth: field.number(
        'Nave Width',
        11,
        [5, 18, 0.1],
        'Interior width of the cathedral.',
      ),
      naveHeight: field.number(
        'Nave Height',
        7,
        [3, 12, 0.1],
        'Interior height of the cathedral.',
      ),
      segmentThickness: field.number(
        'Segment Thickness',
        0.16,
        [0.05, 0.6, 0.01],
        'Thickness of arch pillars and crown beams.',
      ),
      floorExtent: field.number(
        'Floor Extent',
        120,
        [40, 180, 1],
        'Visible depth of the reflective floor.',
      ),
      coreSize: field.number(
        'Core Size',
        1.05,
        [0.2, 2.5, 0.05],
        'Base radius of the central energy core.',
      ),
      particleCount: field.number(
        'Particle Count',
        900,
        [100, 1600, 50],
        'Bounded atmospheric particle count.',
      ),
    },
  ),
  motion: field.group('Motion', 'Camera travel and retained scene motion.', {
    travelSpeed: field.number(
      'Travel Speed',
      4.8,
      [0, 14, 0.1],
      'Forward motion through the arches.',
    ),
    cameraSway: field.number(
      'Camera Sway',
      0.32,
      [0, 2, 0.01],
      'Horizontal cinematic camera movement.',
    ),
    cameraLift: field.number(
      'Camera Lift',
      0.16,
      [0, 1.5, 0.01],
      'Vertical camera motion.',
    ),
    structuralTwist: field.number(
      'Structural Twist',
      0.055,
      [-0.3, 0.3, 0.005],
      'Slow rotation of distant arch gates.',
    ),
    particleDrift: field.number(
      'Particle Drift',
      0.7,
      [0, 3, 0.05],
      'Speed of atmospheric particles.',
    ),
    coreRotation: field.number(
      'Core Rotation',
      0.65,
      [-3, 3, 0.05],
      'Rotation speed of the energy core.',
    ),
  }),
  reactivity: field.group(
    'Music Reactivity',
    'Editable response shaping for canonical audio features.',
    {
      masterResponse: field.number(
        'Master Response',
        1,
        [0, 2.5, 0.05],
        'Global strength of audio-driven motion and light.',
      ),
      bassResponse: field.number(
        'Bass Response',
        1,
        [0, 2.5, 0.05],
        'Structural expansion from bass energy.',
      ),
      midResponse: field.number(
        'Mid Response',
        1,
        [0, 2.5, 0.05],
        'Energy-core response from midrange content.',
      ),
      trebleResponse: field.number(
        'Treble Response',
        1,
        [0, 2.5, 0.05],
        'Particle and color response from treble energy.',
      ),
      onsetResponse: field.number(
        'Onset Response',
        1,
        [0, 2.5, 0.05],
        'Shockwave strength from musical onsets.',
      ),
      fluxResponse: field.number(
        'Flux Response',
        1,
        [0, 2.5, 0.05],
        'Bloom accent from spectral change.',
      ),
      smoothing: field.number(
        'Visual Smoothing',
        0.35,
        [0, 1, 0.05],
        'Additional visual damping applied by the scene.',
      ),
      structurePulse: field.number(
        'Structure Pulse',
        0,
        [0, 1, 0.01],
        'Graph-driven bass structure signal.',
      ),
      coreEnergy: field.number(
        'Core Energy',
        0,
        [0, 1, 0.01],
        'Graph-driven midrange and loudness signal.',
      ),
      spectralShimmer: field.number(
        'Spectral Shimmer',
        0,
        [0, 1, 0.01],
        'Graph-driven treble signal.',
      ),
      shockwaveTrigger: field.number(
        'Shockwave Trigger',
        0,
        [0, 1, 0.01],
        'Graph-driven onset envelope.',
      ),
      bloomAccent: field.number(
        'Bloom Accent',
        0,
        [0, 1, 0.01],
        'Graph-driven spectral-flux envelope.',
      ),
    },
  ),
  lighting: field.group(
    'Light And Atmosphere',
    'Lighting, fog, bloom, and exposure.',
    {
      ambientLevel: field.number(
        'Ambient Level',
        0.12,
        [0, 2, 0.01],
        'Base illumination of non-emissive surfaces.',
      ),
      keyLightIntensity: field.number(
        'Key Light',
        18,
        [0, 60, 0.5],
        'Central point-light intensity.',
      ),
      bloomStrength: field.number(
        'Bloom Strength',
        0.72,
        [0, 3, 0.05],
        'Base emissive bloom strength.',
      ),
      bloomRadius: field.number(
        'Bloom Radius',
        0.62,
        [0, 1, 0.01],
        'Bloom spread around luminous forms.',
      ),
      bloomThreshold: field.number(
        'Bloom Threshold',
        0.18,
        [0, 1, 0.01],
        'Brightness threshold for bloom.',
      ),
      exposure: field.number(
        'Exposure',
        1.05,
        [0.25, 2.5, 0.05],
        'Filmic tone-mapping exposure.',
      ),
      fogDensity: field.number(
        'Fog Density',
        0.014,
        [0, 0.08, 0.001],
        'Exponential atmospheric depth.',
      ),
    },
  ),
});

export const signalCathedralDefaultSettings = createVizSettingDefaults(
  signalCathedralConfig,
);

export const signalCathedralAuthoring = defineVizComponentAuthoring({
  componentId: 'signal-cathedral',
  compatibility: 'render-safe',
  category: 'Production',
  tags: ['music-reactive', 'cinematic', 'three', 'architecture'],
  config: signalCathedralConfig,
  presets: [
    {
      id: 'cathedral',
      name: 'Cathedral',
      description: 'Balanced cyan, violet, and magenta cinematic nave.',
      values: signalCathedralDefaultSettings,
    },
    {
      id: 'pulse-chamber',
      name: 'Pulse Chamber',
      description: 'Tighter red-violet space with stronger bass and onsets.',
      values: {
        palette: {
          background: '#050008',
          primary: '#ff365f',
          secondary: '#8b2cff',
          accent: '#ffb02e',
          fog: '#12020e',
        },
        structure: {
          archCount: 28,
          archSpacing: 3.4,
          naveWidth: 9,
          naveHeight: 6,
          segmentThickness: 0.22,
          floorExtent: 110,
          coreSize: 0.85,
          particleCount: 700,
        },
        motion: {
          travelSpeed: 6.2,
          cameraSway: 0.22,
          cameraLift: 0.12,
          structuralTwist: -0.075,
          particleDrift: 1,
          coreRotation: 1.1,
        },
        reactivity: {
          masterResponse: 1.15,
          bassResponse: 1.35,
          midResponse: 0.9,
          trebleResponse: 0.8,
          onsetResponse: 1.45,
          fluxResponse: 1.2,
          smoothing: 0.22,
          structurePulse: 0,
          coreEnergy: 0,
          spectralShimmer: 0,
          shockwaveTrigger: 0,
          bloomAccent: 0,
        },
        lighting: {
          ambientLevel: 0.08,
          keyLightIntensity: 24,
          bloomStrength: 1.2,
          bloomRadius: 0.48,
          bloomThreshold: 0.14,
          exposure: 1.1,
          fogDensity: 0.028,
        },
      },
    },
    {
      id: 'afterglow',
      name: 'Afterglow',
      description: 'Wide blue-gold atmosphere with slow, soft movement.',
      values: {
        palette: {
          background: '#020711',
          primary: '#76d7ff',
          secondary: '#315cff',
          accent: '#ffd37a',
          fog: '#061126',
        },
        structure: {
          archCount: 20,
          archSpacing: 5.4,
          naveWidth: 13,
          naveHeight: 8.5,
          segmentThickness: 0.12,
          floorExtent: 140,
          coreSize: 1.3,
          particleCount: 1200,
        },
        motion: {
          travelSpeed: 3.2,
          cameraSway: 0.5,
          cameraLift: 0.24,
          structuralTwist: 0.035,
          particleDrift: 0.45,
          coreRotation: 0.35,
        },
        reactivity: {
          masterResponse: 0.9,
          bassResponse: 0.8,
          midResponse: 1.15,
          trebleResponse: 1.25,
          onsetResponse: 0.75,
          fluxResponse: 0.9,
          smoothing: 0.55,
          structurePulse: 0,
          coreEnergy: 0,
          spectralShimmer: 0,
          shockwaveTrigger: 0,
          bloomAccent: 0,
        },
        lighting: {
          ambientLevel: 0.18,
          keyLightIntensity: 14,
          bloomStrength: 0.9,
          bloomRadius: 0.78,
          bloomThreshold: 0.22,
          exposure: 1,
          fogDensity: 0.018,
        },
      },
    },
  ],
});
