import {
  defineVizComponentAuthoring,
  v,
} from "@viz-engine/components-core";

export const signalCathedralAuthoring = defineVizComponentAuthoring({
  componentId: "signal-cathedral",
  compatibility: "render-safe",
  category: "Production",
  tags: ["music-reactive", "cinematic", "three", "architecture"],
  config: v.config({
    palette: v.group(
      {
        label: "Palette",
        description: "The scene's architectural and atmospheric colors.",
      },
      {
        background: v.color({
          label: "Background",
          description: "Deep background color behind the structure.",
          defaultValue: "#02030d",
        }),
        primary: v.color({
          label: "Primary Light",
          description: "Main arch and core color.",
          defaultValue: "#5cf5ff",
        }),
        secondary: v.color({
          label: "Secondary Light",
          description: "Alternating structural light color.",
          defaultValue: "#8b5cff",
        }),
        accent: v.color({
          label: "Accent",
          description: "Shockwave and high-frequency accent color.",
          defaultValue: "#ff3fcf",
        }),
        fog: v.color({
          label: "Fog",
          description: "Atmospheric depth color.",
          defaultValue: "#07051c",
        }),
      },
    ),
    structure: v.group(
      {
        label: "Structure",
        description: "Dimensions and density of the luminous cathedral.",
      },
      {
        archCount: v.number({
          label: "Arch Count",
          description: "Number of repeating arch gates.",
          defaultValue: 24,
          min: 8,
          max: 32,
          step: 1,
        }),
        archSpacing: v.number({
          label: "Arch Spacing",
          description: "Depth between consecutive gates.",
          defaultValue: 4.2,
          min: 2,
          max: 8,
          step: 0.1,
        }),
        naveWidth: v.number({
          label: "Nave Width",
          description: "Interior width of the cathedral.",
          defaultValue: 11,
          min: 5,
          max: 18,
          step: 0.1,
        }),
        naveHeight: v.number({
          label: "Nave Height",
          description: "Interior height of the cathedral.",
          defaultValue: 7,
          min: 3,
          max: 12,
          step: 0.1,
        }),
        segmentThickness: v.number({
          label: "Segment Thickness",
          description: "Thickness of arch pillars and crown beams.",
          defaultValue: 0.16,
          min: 0.05,
          max: 0.6,
          step: 0.01,
        }),
        floorExtent: v.number({
          label: "Floor Extent",
          description: "Visible depth of the reflective floor.",
          defaultValue: 120,
          min: 40,
          max: 180,
          step: 1,
        }),
        coreSize: v.number({
          label: "Core Size",
          description: "Base radius of the central energy core.",
          defaultValue: 1.05,
          min: 0.2,
          max: 2.5,
          step: 0.05,
        }),
        particleCount: v.number({
          label: "Particle Count",
          description: "Bounded atmospheric particle count.",
          defaultValue: 900,
          min: 100,
          max: 1600,
          step: 50,
        }),
      },
    ),
    motion: v.group(
      {
        label: "Motion",
        description: "Camera travel and retained scene motion.",
      },
      {
        travelSpeed: v.number({
          label: "Travel Speed",
          description: "Forward motion through the arches.",
          defaultValue: 4.8,
          min: 0,
          max: 14,
          step: 0.1,
        }),
        cameraSway: v.number({
          label: "Camera Sway",
          description: "Horizontal cinematic camera movement.",
          defaultValue: 0.32,
          min: 0,
          max: 2,
          step: 0.01,
        }),
        cameraLift: v.number({
          label: "Camera Lift",
          description: "Vertical camera motion.",
          defaultValue: 0.16,
          min: 0,
          max: 1.5,
          step: 0.01,
        }),
        structuralTwist: v.number({
          label: "Structural Twist",
          description: "Slow rotation of distant arch gates.",
          defaultValue: 0.055,
          min: -0.3,
          max: 0.3,
          step: 0.005,
        }),
        particleDrift: v.number({
          label: "Particle Drift",
          description: "Speed of atmospheric particles.",
          defaultValue: 0.7,
          min: 0,
          max: 3,
          step: 0.05,
        }),
        coreRotation: v.number({
          label: "Core Rotation",
          description: "Rotation speed of the energy core.",
          defaultValue: 0.65,
          min: -3,
          max: 3,
          step: 0.05,
        }),
      },
    ),
    reactivity: v.group(
      {
        label: "Music Reactivity",
        description: "Editable response shaping for canonical audio features.",
      },
      {
        masterResponse: v.number({
          label: "Master Response",
          description: "Global strength of audio-driven motion and light.",
          defaultValue: 1,
          min: 0,
          max: 2.5,
          step: 0.05,
        }),
        bassResponse: v.number({
          label: "Bass Response",
          description: "Structural expansion from bass energy.",
          defaultValue: 1,
          min: 0,
          max: 2.5,
          step: 0.05,
        }),
        midResponse: v.number({
          label: "Mid Response",
          description: "Energy-core response from midrange content.",
          defaultValue: 1,
          min: 0,
          max: 2.5,
          step: 0.05,
        }),
        trebleResponse: v.number({
          label: "Treble Response",
          description: "Particle and color response from treble energy.",
          defaultValue: 1,
          min: 0,
          max: 2.5,
          step: 0.05,
        }),
        onsetResponse: v.number({
          label: "Onset Response",
          description: "Shockwave strength from musical onsets.",
          defaultValue: 1,
          min: 0,
          max: 2.5,
          step: 0.05,
        }),
        fluxResponse: v.number({
          label: "Flux Response",
          description: "Bloom accent from spectral change.",
          defaultValue: 1,
          min: 0,
          max: 2.5,
          step: 0.05,
        }),
        smoothing: v.number({
          label: "Visual Smoothing",
          description: "Additional visual damping applied by the scene.",
          defaultValue: 0.35,
          min: 0,
          max: 1,
          step: 0.05,
        }),
        structurePulse: v.number({
          label: "Structure Pulse",
          description: "Graph-driven bass structure signal.",
          defaultValue: 0,
          min: 0,
          max: 1,
          step: 0.01,
        }),
        coreEnergy: v.number({
          label: "Core Energy",
          description: "Graph-driven midrange and loudness signal.",
          defaultValue: 0,
          min: 0,
          max: 1,
          step: 0.01,
        }),
        spectralShimmer: v.number({
          label: "Spectral Shimmer",
          description: "Graph-driven treble signal.",
          defaultValue: 0,
          min: 0,
          max: 1,
          step: 0.01,
        }),
        shockwaveTrigger: v.number({
          label: "Shockwave Trigger",
          description: "Graph-driven onset envelope.",
          defaultValue: 0,
          min: 0,
          max: 1,
          step: 0.01,
        }),
        bloomAccent: v.number({
          label: "Bloom Accent",
          description: "Graph-driven spectral-flux envelope.",
          defaultValue: 0,
          min: 0,
          max: 1,
          step: 0.01,
        }),
      },
    ),
    lighting: v.group(
      {
        label: "Light And Atmosphere",
        description: "Lighting, fog, bloom, and exposure.",
      },
      {
        ambientLevel: v.number({
          label: "Ambient Level",
          description: "Base illumination of non-emissive surfaces.",
          defaultValue: 0.12,
          min: 0,
          max: 2,
          step: 0.01,
        }),
        keyLightIntensity: v.number({
          label: "Key Light",
          description: "Central point-light intensity.",
          defaultValue: 18,
          min: 0,
          max: 60,
          step: 0.5,
        }),
        bloomStrength: v.number({
          label: "Bloom Strength",
          description: "Base emissive bloom strength.",
          defaultValue: 0.72,
          min: 0,
          max: 3,
          step: 0.05,
        }),
        bloomRadius: v.number({
          label: "Bloom Radius",
          description: "Bloom spread around luminous forms.",
          defaultValue: 0.62,
          min: 0,
          max: 1,
          step: 0.01,
        }),
        bloomThreshold: v.number({
          label: "Bloom Threshold",
          description: "Brightness threshold for bloom.",
          defaultValue: 0.18,
          min: 0,
          max: 1,
          step: 0.01,
        }),
        exposure: v.number({
          label: "Exposure",
          description: "Filmic tone-mapping exposure.",
          defaultValue: 1.05,
          min: 0.25,
          max: 2.5,
          step: 0.05,
        }),
        fogDensity: v.number({
          label: "Fog Density",
          description: "Exponential atmospheric depth.",
          defaultValue: 0.014,
          min: 0,
          max: 0.08,
          step: 0.001,
        }),
      },
    ),
  }),
  presets: [
    {
      id: "cathedral",
      name: "Cathedral",
      description: "Balanced cyan, violet, and magenta cinematic nave.",
      values: {
        palette: {
          background: "#02030d",
          primary: "#5cf5ff",
          secondary: "#8b5cff",
          accent: "#ff3fcf",
          fog: "#07051c",
        },
        structure: {
          archCount: 24,
          archSpacing: 4.2,
          naveWidth: 11,
          naveHeight: 7,
          segmentThickness: 0.16,
          floorExtent: 120,
          coreSize: 1.05,
          particleCount: 900,
        },
        motion: {
          travelSpeed: 4.8,
          cameraSway: 0.32,
          cameraLift: 0.16,
          structuralTwist: 0.055,
          particleDrift: 0.7,
          coreRotation: 0.65,
        },
        reactivity: {
          masterResponse: 1,
          bassResponse: 1,
          midResponse: 1,
          trebleResponse: 1,
          onsetResponse: 1,
          fluxResponse: 1,
          smoothing: 0.35,
          structurePulse: 0,
          coreEnergy: 0,
          spectralShimmer: 0,
          shockwaveTrigger: 0,
          bloomAccent: 0,
        },
        lighting: {
          ambientLevel: 0.12,
          keyLightIntensity: 18,
          bloomStrength: 0.72,
          bloomRadius: 0.62,
          bloomThreshold: 0.18,
          exposure: 1.05,
          fogDensity: 0.014,
        },
      },
    },
    {
      id: "pulse-chamber",
      name: "Pulse Chamber",
      description: "Tighter red-violet space with stronger bass and onsets.",
      values: {
        palette: {
          background: "#050008",
          primary: "#ff365f",
          secondary: "#8b2cff",
          accent: "#ffb02e",
          fog: "#12020e",
        },
        structure: {
          archCount: 28,
          archSpacing: 3.4,
          naveWidth: 9,
          naveHeight: 6,
          segmentThickness: 0.22,
          floorExtent: 110,
          coreSize: 0.85,
          particleCount: 700,
        },
        motion: {
          travelSpeed: 6.2,
          cameraSway: 0.22,
          cameraLift: 0.12,
          structuralTwist: -0.075,
          particleDrift: 1,
          coreRotation: 1.1,
        },
        reactivity: {
          masterResponse: 1.15,
          bassResponse: 1.35,
          midResponse: 0.9,
          trebleResponse: 0.8,
          onsetResponse: 1.45,
          fluxResponse: 1.2,
          smoothing: 0.22,
          structurePulse: 0,
          coreEnergy: 0,
          spectralShimmer: 0,
          shockwaveTrigger: 0,
          bloomAccent: 0,
        },
        lighting: {
          ambientLevel: 0.08,
          keyLightIntensity: 24,
          bloomStrength: 1.2,
          bloomRadius: 0.48,
          bloomThreshold: 0.14,
          exposure: 1.1,
          fogDensity: 0.028,
        },
      },
    },
    {
      id: "afterglow",
      name: "Afterglow",
      description: "Wide blue-gold atmosphere with slow, soft movement.",
      values: {
        palette: {
          background: "#020711",
          primary: "#76d7ff",
          secondary: "#315cff",
          accent: "#ffd37a",
          fog: "#061126",
        },
        structure: {
          archCount: 20,
          archSpacing: 5.4,
          naveWidth: 13,
          naveHeight: 8.5,
          segmentThickness: 0.12,
          floorExtent: 140,
          coreSize: 1.3,
          particleCount: 1200,
        },
        motion: {
          travelSpeed: 3.2,
          cameraSway: 0.5,
          cameraLift: 0.24,
          structuralTwist: 0.035,
          particleDrift: 0.45,
          coreRotation: 0.35,
        },
        reactivity: {
          masterResponse: 0.9,
          bassResponse: 0.8,
          midResponse: 1.15,
          trebleResponse: 1.25,
          onsetResponse: 0.75,
          fluxResponse: 0.9,
          smoothing: 0.55,
          structurePulse: 0,
          coreEnergy: 0,
          spectralShimmer: 0,
          shockwaveTrigger: 0,
          bloomAccent: 0,
        },
        lighting: {
          ambientLevel: 0.18,
          keyLightIntensity: 14,
          bloomStrength: 0.9,
          bloomRadius: 0.78,
          bloomThreshold: 0.22,
          exposure: 1,
          fogDensity: 0.018,
        },
      },
    },
  ],
});
