import { v } from '../config/config';
import { createComponent } from '../config/create-component';

const MorphShapes = createComponent({
  name: 'Morph Shapes',
  description:
    'Instanced morph between two hardcoded shapes with explosion overlay',
  config: v.config({
    morphT: v.number({
      label: 'Morph',
      description: 'Morph between shapes',
      defaultValue: 0,
      min: 0,
      max: 1,
      step: 0.01,
    }),
    explosionShift: v.number({
      label: 'Explosion Shift',
      description: 'Explode outward along normals',
      defaultValue: 0,
      min: 0,
      max: 100,
      step: 0.1,
    }),
    animationSpeed: v.number({
      label: 'Animation Speed',
      description: 'Follow speed toward target',
      defaultValue: 0.08,
      min: 0.01,
      max: 0.2,
      step: 0.01,
    }),
    color: v.color({
      label: 'Color',
      defaultValue: 'rgb(0, 200, 255)',
      description: 'Instance color',
    }),
    gridSize: v.number({
      label: 'Grid Size',
      description: 'Instance resolution of cube frame',
      defaultValue: 5,
      min: 1,
      max: 100,
      step: 1,
    }),
    modelPointCount: v.number({
      label: 'Model Points',
      description: 'Number of points for model shapes',
      defaultValue: 15000,
      min: 1,
      max: 10000,
      step: 10,
    }),
    modelEvenness: v.number({
      label: 'Evenness',
      description: 'Higher values push points apart more (blue-noise sampling)',
      defaultValue: 0.7,
      min: 0.2,
      max: 1.0,
      step: 0.05,
    }),
    sphereSize: v.number({
      label: 'Sphere Size',
      description: 'Radius of each sphere instance',
      defaultValue: 0.15,
      min: 0.01,
      max: 1.0,
      step: 0.01,
    }),
    additiveGlow: v.toggle({
      label: 'Additive Glow',
      description: 'Use additive blending and disable depth for glowy look',
      defaultValue: false,
    }),
    glowIntensity: v.number({
      label: 'Glow Intensity',
      description: 'Boost factor for glow (emissive simulation)',
      defaultValue: 1.0,
      min: 0.2,
      max: 5.0,
      step: 0.1,
    }),
    rotation: v.group(
      { label: 'Rotation', description: 'Rotate the whole shape' },
      {
        axis: v.vector3({
          label: 'Axis',
          description: 'Rotation axis as a vector',
          defaultValue: { x: 0, y: 1, z: 0 },
          min: -1,
          max: 1,
          step: 0.01,
        }),
        speed: v.number({
          label: 'Speed',
          description: 'Angular speed (radians/sec)',
          defaultValue: 0.5,
          min: -5,
          max: 5,
          step: 0.01,
        }),
      },
    ),
    shapeASettings: v.group(
      { label: 'Shape A Settings' },
      {
        shape: v.select({
          label: 'Shape',
          description: 'Starting shape',
          defaultValue: 'cube',
          options: ['cube', 'pyramid', 'model', 'custom-text'],
        }),
        textFontUrl: v.text({
          label: 'Font URL (.ttf)',
          description:
            'Optional TTF font URL (CORS-enabled, e.g., Google Fonts TTF) for custom text',
          defaultValue: '',
          visibleIf: (vals) => vals.shapeASettings?.shape === 'custom-text',
        }),
        modelUrl: v.file({
          label: 'Model (.glb/.gltf)',
          description: 'Path or URL when shape is set to model',
          defaultValue: '',
          allowedExtensions: ['.glb', '.gltf'],
          visibleIf: (vals) => vals.shapeASettings?.shape === 'model',
        }),
        text: v.text({
          label: 'Custom Text',
          description: 'Shown when shape is custom-text',
          defaultValue: '',
          visibleIf: (vals) => vals.shapeASettings?.shape === 'custom-text',
        }),
        textSize: v.number({
          label: 'Text Size',
          description: 'Font size of 3D text',
          defaultValue: 1,
          min: 0.1,
          max: 10,
          step: 0.1,
          visibleIf: (vals) => vals.shapeASettings?.shape === 'custom-text',
        }),
        textDepth: v.number({
          label: 'Text Depth',
          description: 'Extrusion depth of 3D text',
          defaultValue: 0.2,
          min: 0.01,
          max: 2,
          step: 0.01,
          visibleIf: (vals) => vals.shapeASettings?.shape === 'custom-text',
        }),
        position: v.vector3({
          label: 'Position',
          description: 'Offset in world units',
          defaultValue: { x: 0, y: 0, z: 0 },
          min: -10,
          max: 10,
          step: 0.01,
        }),
        rotation: v.vector3({
          label: 'Rotation (deg)',
          description: 'Euler rotation in degrees',
          defaultValue: { x: 0, y: 0, z: 0 },
          min: -360,
          max: 360,
          step: 0.1,
        }),
      },
    ),
    shapeBSettings: v.group(
      { label: 'Shape B Settings' },
      {
        shape: v.select({
          label: 'Shape',
          description: 'Target shape',
          defaultValue: 'pyramid',
          options: ['cube', 'pyramid', 'model', 'custom-text'],
        }),
        textFontUrl: v.text({
          label: 'Font URL (.ttf)',
          description:
            'Optional TTF font URL (CORS-enabled, e.g., Google Fonts TTF) for custom text',
          defaultValue: '',
          visibleIf: (vals) => vals.shapeBSettings?.shape === 'custom-text',
        }),
        modelUrl: v.file({
          label: 'Model (.glb/.gltf)',
          description: 'Path or URL when shape is set to model',
          defaultValue: '',
          allowedExtensions: ['.glb', '.gltf'],
          visibleIf: (vals) => vals.shapeBSettings?.shape === 'model',
        }),
        text: v.text({
          label: 'Custom Text',
          description: 'Shown when shape is custom-text',
          defaultValue: '',
          visibleIf: (vals) => vals.shapeBSettings?.shape === 'custom-text',
        }),
        textSize: v.number({
          label: 'Text Size',
          description: 'Font size of 3D text',
          defaultValue: 1,
          min: 0.1,
          max: 10,
          step: 0.1,
          visibleIf: (vals) => vals.shapeBSettings?.shape === 'custom-text',
        }),
        textDepth: v.number({
          label: 'Text Depth',
          description: 'Extrusion depth of 3D text',
          defaultValue: 0.2,
          min: 0.01,
          max: 2,
          step: 0.01,
          visibleIf: (vals) => vals.shapeBSettings?.shape === 'custom-text',
        }),
        position: v.vector3({
          label: 'Position',
          description: 'Offset in world units',
          defaultValue: { x: 0, y: 0, z: 0 },
          min: -10,
          max: 10,
          step: 0.01,
        }),
        rotation: v.vector3({
          label: 'Rotation (deg)',
          description: 'Euler rotation in degrees',
          defaultValue: { x: 0, y: 0, z: 0 },
          min: -180,
          max: 180,
          step: 0.1,
        }),
      },
    ),
  }),
});

export default MorphShapes;
