import { v } from '../config/config';
import { createComponent } from '../config/create-component';

const NeuralNetwork = createComponent({
  name: 'Neural Network',
  description: 'Realistic procedural neuron structures - fly through the brain',
  config: v.config({
    neuronCount: v.number({
      label: 'Neuron Count',
      description: 'Number of neurons to display',
      defaultValue: 30,
      min: 1,
      max: 50,
      step: 1,
    }),
    seed: v.number({
      label: 'Neuron Seed',
      description: 'Seed for procedural neuron generation',
      defaultValue: 42,
      min: 1,
      max: 10000,
      step: 1,
    }),
    tubeRadius: v.number({
      label: 'Tube Thickness',
      description: 'Radius of the dendrite tubes',
      defaultValue: 0.25,
      min: 0.05,
      max: 1,
      step: 0.05,
    }),
    neuronColor: v.color({
      label: 'Neuron Color',
      description: 'Base color of the neuron',
      defaultValue: '#00CED1',
    }),
    somaEmission: v.color({
      label: 'Soma Glow',
      description: 'Emission color of the cell body',
      defaultValue: 'rgb(255, 138, 201)',
    }),
    emissiveIntensity: v.number({
      label: 'Glow Intensity',
      description: 'How much the soma glows',
      defaultValue: 2,
      min: 0,
      max: 5,
      step: 0.1,
    }),
    metalness: v.number({
      label: 'Metalness',
      description: 'Metallic appearance',
      defaultValue: 0,
      min: 0,
      max: 1,
      step: 0.05,
    }),
    roughness: v.number({
      label: 'Roughness',
      description: 'Surface roughness',
      defaultValue: 0.9,
      min: 0,
      max: 1,
      step: 0.05,
    }),
    fresnelPower: v.number({
      label: 'Rim Glow',
      description: 'Fresnel rim lighting intensity',
      defaultValue: 3,
      min: 0.5,
      max: 8,
      step: 0.5,
    }),
    growth: v.number({
      label: 'Growth',
      description: 'Dendrite growth animation (0 = just soma, 1 = fully grown)',
      defaultValue: 1,
      min: 0,
      max: 1,
      step: 0.01,
    }),
    dendriteReach: v.number({
      label: 'Dendrite Reach',
      description:
        'How far dendrites extend from soma (15+ to connect neurons)',
      defaultValue: 20,
      min: 5,
      max: 40,
      step: 1,
    }),
    trigger: v.toggle({
      label: 'Fire Neurons',
      description: 'Toggle on to fire neural signals through the network',
      defaultValue: false,
    }),
    signalSpeed: v.number({
      label: 'Signal Speed',
      description: 'How fast signals travel along dendrites',
      defaultValue: 30,
      min: 1,
      max: 40,
      step: 0.5,
    }),
    signalSize: v.number({
      label: 'Signal Orb Size',
      description: 'Radius of traveling signal orbs',
      defaultValue: 0.2,
      min: 0.1,
      max: 2,
      step: 0.1,
    }),
    activationDecay: v.number({
      label: 'Activation Decay',
      description: 'How quickly neurons fade after activation',
      defaultValue: 0.4,
      min: 0,
      max: 10,
      step: 0.5,
    }),
    postProcessing: v.group(
      {
        label: 'Post Processing',
        description: 'Bloom and depth of field effects',
      },
      {
        bloom: v.toggle({
          label: 'Bloom Enabled',
          description: 'Enable bloom glow effect',
          defaultValue: false,
        }),
        bloomStrength: v.number({
          label: 'Bloom Strength',
          description: 'Intensity of the bloom glow effect',
          defaultValue: 0.2,
          min: 0,
          max: 3,
          step: 0.01,
        }),
        bloomRadius: v.number({
          label: 'Bloom Radius',
          description: 'Size of the bloom glow spread',
          defaultValue: 0.8,
          min: 0,
          max: 1,
          step: 0.01,
        }),
        bloomThreshold: v.number({
          label: 'Bloom Threshold',
          description: 'Brightness threshold for bloom effect',
          defaultValue: 0.3,
          min: 0,
          max: 1,
          step: 0.01,
        }),
        depthOfField: v.toggle({
          label: 'Depth of Field',
          description: 'Enable cinematic shallow focus effect',
          defaultValue: true,
        }),
        dofFocus: v.number({
          label: 'DOF Focus Distance',
          description: 'Distance where objects are in focus',
          defaultValue: 10,
          min: 1,
          max: 50,
          step: 0.5,
        }),
        dofAperture: v.number({
          label: 'DOF Aperture',
          description: 'Blur amount (lower = more blur)',
          defaultValue: 0.0005,
          min: 0.0001,
          max: 0.002,
          step: 0.0001,
        }),
      },
    ),
  }),
  defaultNetworks: {
    'postProcessing.dofFocus': 'dof-focus-slow-sine',
    trigger: 'neural-fire-on-kick',
    seed: 'neural-seed-snare-cycle',
  },
});

export default NeuralNetwork;
