import { defineVizComponentAuthoring, settingCondition, v } from './schema.js';

type NoisePreset = [
  name: string,
  noise: [
    type: string,
    scale: number,
    octaves: number,
    lacunarity: number,
    gain: number,
  ],
  animation: [
    speed: number,
    flowX: number,
    flowY: number,
    rotationSpeed: number,
  ],
  distortion: [enabled: boolean, amount: number, scale: number],
  color: [
    mode: string,
    color1: string,
    color2: string,
    color3: string,
    hueShift: number,
    saturation: number,
  ],
  output: [
    brightness: number,
    contrast: number,
    invert: boolean,
    posterize: number,
  ],
];

const preset = ([
  name,
  [type, scale, octaves, lacunarity, gain],
  [speed, flowX, flowY, rotationSpeed],
  [enabled, amount, distortionScale],
  [mode, color1, color2, color3, hueShift, saturation],
  [brightness, contrast, invert, posterize],
]: NoisePreset) => ({
  name,
  values: {
    noise: { type, scale, octaves, lacunarity, gain },
    animation: { speed, flowX, flowY, rotationSpeed },
    distortion: { enabled, amount, scale: distortionScale },
    color: { mode, color1, color2, color3, hueShift, saturation },
    output: { brightness, contrast, invert, posterize },
  },
});

export const noiseShaderAuthoring = defineVizComponentAuthoring({
  componentId: 'noise-shader',
  compatibility: 'render-safe',
  presets: [
    preset([
      'Init',
      ['fbm', 3.0, 4, 2.0, 0.5],
      [1.0, 0.0, 0.0, 0.0],
      [false, 1.0, 2.0],
      ['gradient', '#000000', '#ffffff', '#ff0000', 1.0, 1.0],
      [1.0, 1.0, false, 0],
    ]),
    preset([
      'White Tiger (Monochrome)',
      ['simplex', 0.6, 2, 3.0, 0.3],
      [2.8, 0.02, 0.02, 0.0],
      [true, 3.5, 1.0],
      ['monochrome', '#ffffff', '#ffffff', '#ffffff', 1.0, 0.0],
      [1.99, 3.0, true, 1],
    ]),
    preset([
      'Flowing Ink (Monochrome)',
      ['perlin', 1.9, 2, 3.0, 0.3],
      [2.8, 0.0, 0.0, 0.0],
      [true, 4.0, 1.5],
      ['monochrome', '#ffffff', '#ffffff', '#ffffff', 1.0, 0.0],
      [1.99, 3.0, false, 1],
    ]),
    preset([
      'Flowing Liquid (Monochrome)',
      ['perlin', 8.0, 2, 3.0, 0.3],
      [2.5, 0.0, 0.2, 0.0],
      [true, 4.0, 1.5],
      ['monochrome', '#ffffff', '#ffffff', '#ffffff', 1.0, 0.0],
      [1.5, 4.0, true, 3],
    ]),
    preset([
      'Smoke (Monochrome)',
      ['perlin', 0.6, 2, 3, 0.3],
      [7, 0, 0, 0],
      [true, 4, 1.5],
      ['monochrome', '#ffffff', '#ffffff', '#ffffff', 1, 0],
      [1.49, 3, true, 0],
    ]),
    preset([
      'Plasma Wave',
      ['simplex', 4.0, 4, 2.0, 0.5],
      [1.8, 0.15, 0.15, 0.4],
      [true, 2.0, 2.5],
      ['hue-shift', '#ff0000', '#00ff00', '#0000ff', 4.0, 1.9],
      [1.7, 1.6, false, 0],
    ]),
    preset([
      'Lava Lamp',
      ['fbm', 0.8, 5, 2.0, 0.6],
      [0.8, 0.0, 0.12, 0.08],
      [true, 2.5, 1.2],
      ['palette', '#ff0000', '#ff6600', '#ffff00', 1.0, 1.8],
      [1.5, 1.3, false, 0],
    ]),
    preset([
      'Aurora Borealis',
      ['fbm', 0.4, 3, 2.0, 0.5],
      [0.2, 0.15, 0.03, 0.0],
      [true, 0.5, 1.0],
      ['palette', '#001a33', '#00ff88', '#8800ff', 1.0, 1.6],
      [1.4, 1.2, false, 0],
    ]),
    preset([
      'Fire',
      ['fbm', 1.2, 4, 2.0, 0.5],
      [1.0, 0.0, -0.2, 0.0],
      [true, 1.0, 1.5],
      ['palette', '#000000', '#ff3300', '#ffff00', 1.0, 2.0],
      [2.0, 2.0, false, 0],
    ]),
    preset([
      'Clouds',
      ['fbm', 0.6, 5, 2.0, 0.5],
      [0.15, 0.02, 0.008, 0.0],
      [false, 1.0, 2.0],
      ['gradient', '#4a90e2', '#ffffff', '#0000ff', 1.0, 0.8],
      [1.2, 0.9, false, 0],
    ]),
    preset([
      'Marble',
      ['perlin', 2.0, 4, 2.0, 0.5],
      [0.1, 0.0, 0.0, 0.05],
      [true, 2.0, 1.0],
      ['gradient', '#1a1a1a', '#f0f0f0', '#0000ff', 1.0, 0.3],
      [1.1, 1.8, false, 0],
    ]),
    preset([
      'Oil Slick',
      ['simplex', 2.5, 4, 2.0, 0.5],
      [0.3, 0.0, 0.0, 0.08],
      [true, 0.8, 2.0],
      ['hue-shift', '#ff0000', '#00ff00', '#0000ff', 1.5, 1.8],
      [1.3, 1.5, false, 0],
    ]),
    preset([
      'Hard Edge Balls',
      ['cellular', 8.0, 4, 2.0, 0.5],
      [3.0, 0.0, 0.0, 0.0],
      [false, 1.0, 2.0],
      ['monochrome', '#ffffff', '#ffffff', '#0000ff', 1.0, 1.0],
      [1.0, 2.0, false, 2],
    ]),
    preset([
      'Watercolor',
      ['fbm', 1.8, 5, 1.8, 0.65],
      [0.6, 0.05, -0.08, 0.03],
      [true, 1.5, 2.5],
      ['palette', '#ff6b9d', '#c44569', '#4a69bd', 1.0, 1.3],
      [1.3, 1.1, false, 0],
    ]),
  ],
  config: v.config({
    noise: v.group(
      {
        label: 'Noise Settings',
        description: 'Core noise generation parameters',
      },
      {
        type: v.select({
          label: 'Noise Type',
          description: 'Type of noise algorithm',
          defaultValue: 'fbm',
          options: ['perlin', 'simplex', 'fbm', 'voronoi', 'cellular'],
        }),
        scale: v.number({
          label: 'Scale',
          description: 'Zoom level of the noise pattern',
          defaultValue: 3.0,
          min: 0.1,
          max: 20.0,
          step: 0.1,
        }),
        octaves: v.number({
          label: 'Octaves',
          description: 'Detail layers (for FBM)',
          defaultValue: 4,
          min: 1,
          max: 8,
          step: 1,
          visibleWhen: settingCondition('noise.type', 'equals', 'fbm'),
        }),
        lacunarity: v.number({
          label: 'Lacunarity',
          description: 'Frequency multiplier per octave',
          defaultValue: 2.0,
          min: 1.0,
          max: 4.0,
          step: 0.1,
          visibleWhen: settingCondition('noise.type', 'equals', 'fbm'),
        }),
        gain: v.number({
          label: 'Gain',
          description: 'Amplitude multiplier per octave',
          defaultValue: 0.5,
          min: 0.0,
          max: 1.0,
          step: 0.01,
          visibleWhen: settingCondition('noise.type', 'equals', 'fbm'),
        }),
      },
    ),
    animation: v.group(
      {
        label: 'Animation',
        description: 'Motion and time-based effects',
      },
      {
        speed: v.number({
          label: 'Speed',
          description: 'Animation speed multiplier',
          defaultValue: 1.0,
          min: 0.0,
          max: 10.0,
          step: 0.1,
        }),
        flowX: v.number({
          label: 'Flow X',
          description: 'Horizontal flow/drift speed',
          defaultValue: 0.0,
          min: -2.0,
          max: 2.0,
          step: 0.01,
        }),
        flowY: v.number({
          label: 'Flow Y',
          description: 'Vertical flow/drift speed',
          defaultValue: 0.0,
          min: -2.0,
          max: 2.0,
          step: 0.01,
        }),
        rotationSpeed: v.number({
          label: 'Rotation Speed',
          description: 'Rotation animation speed',
          defaultValue: 0.0,
          min: -2.0,
          max: 2.0,
          step: 0.01,
        }),
      },
    ),
    distortion: v.group(
      {
        label: 'Distortion',
        description: 'Warping and distortion effects',
      },
      {
        enabled: v.toggle({
          label: 'Enable Distortion',
          description: 'Apply domain distortion to noise',
          defaultValue: false,
        }),
        amount: v.number({
          label: 'Amount',
          description: 'Strength of distortion',
          defaultValue: 1.0,
          min: 0.0,
          max: 5.0,
          step: 0.1,
          visibleWhen: settingCondition('distortion.enabled', 'equals', true),
        }),
        scale: v.number({
          label: 'Scale',
          description: 'Frequency of distortion pattern',
          defaultValue: 2.0,
          min: 0.1,
          max: 10.0,
          step: 0.1,
          visibleWhen: settingCondition('distortion.enabled', 'equals', true),
        }),
      },
    ),
    color: v.group(
      {
        label: 'Color',
        description: 'Color mapping and palette',
      },
      {
        mode: v.select({
          label: 'Color Mode',
          description: 'How to map noise to colors',
          defaultValue: 'gradient',
          options: ['gradient', 'palette', 'hue-shift', 'monochrome'],
        }),
        color1: v.color({
          label: 'Color 1',
          description: 'First color (gradient start, or monochrome)',
          defaultValue: '#000000',
          visibleWhen: settingCondition('color.mode', 'in', [
            'gradient',
            'palette',
            'monochrome',
          ]),
        }),
        color2: v.color({
          label: 'Color 2',
          description: 'Second color (gradient end)',
          defaultValue: '#ffffff',
          visibleWhen: settingCondition('color.mode', 'in', [
            'gradient',
            'palette',
          ]),
        }),
        color3: v.color({
          label: 'Color 3',
          description: 'Third color (palette mode)',
          defaultValue: '#ff0000',
          visibleWhen: settingCondition('color.mode', 'equals', 'palette'),
        }),
        hueShift: v.number({
          label: 'Hue Shift Speed',
          description: 'Hue rotation speed',
          defaultValue: 1.0,
          min: 0.0,
          max: 5.0,
          step: 0.1,
          visibleWhen: settingCondition('color.mode', 'equals', 'hue-shift'),
        }),
        saturation: v.number({
          label: 'Saturation',
          description: 'Color saturation',
          defaultValue: 1.0,
          min: 0.0,
          max: 2.0,
          step: 0.01,
          visibleWhen: settingCondition('color.mode', 'in', [
            'gradient',
            'palette',
            'hue-shift',
          ]),
        }),
      },
    ),
    output: v.group(
      {
        label: 'Output',
        description: 'Final output adjustments',
      },
      {
        brightness: v.number({
          label: 'Brightness',
          description: 'Overall brightness',
          defaultValue: 1.0,
          min: 0.0,
          max: 3.0,
          step: 0.01,
        }),
        contrast: v.number({
          label: 'Contrast',
          description: 'Contrast adjustment',
          defaultValue: 1.0,
          min: 0.0,
          max: 3.0,
          step: 0.01,
        }),
        invert: v.toggle({
          label: 'Invert',
          description: 'Invert the output colors',
          defaultValue: false,
        }),
        posterize: v.number({
          label: 'Posterize Levels',
          description: 'Color banding effect (0 = off)',
          defaultValue: 0,
          min: 0,
          max: 16,
          step: 1,
        }),
      },
    ),
  }),
});
